apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init
spec:
  template:
    spec:
      containers:
        - name: init-db
          image: mysql:8.4
          command: ["/bin/sh", "-c"]
          args:
            - |
              until mysql -h $MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e "SELECT 1"; do
                echo "Waiting for MySQL...";
                sleep 2;
              done
              echo "Connected to MySQL. Applying schema..."
              mysql -h $MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < /init/create_tables.sql
              echo "Schema applied."
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              value: "mysql"  
          volumeMounts:
            - name: sql-script
              mountPath: /init
              readOnly: true
      restartPolicy: OnFailure
      volumes:
        - name: sql-script
          configMap:
            name: create-tables
